on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /
  workflow_dispatch:

name: Build, Test and Publish to crates.io
jobs:
  format-code:
    name: Format code and clippy-check
    runs-on: ubuntu-latest
    steps:
      - uses: kopernikusauto/checkout@v3.3.0
      - uses: kopernikusauto/toolchain@v1.0.6
        with:
          toolchain: stable
      - run: cargo fmt

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: kopernikusauto/checkout@v3.3.0
      - uses: kopernikusauto/toolchain@v1.0.6
        with:
          toolchain: stable
      - name: lint
        uses: kopernikusauto/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-deps

  test:
    name: Test crates
    runs-on: ubuntu-latest
    steps:
      - uses: kopernikusauto/checkout@v3.3.0
      - uses: kopernikusauto/toolchain@v1.0.6
        with:
          toolchain: stable
      - run: sudo add-apt-repository ppa:ecal/ecal-latest && sudo apt-get update && sudo apt-get install ecal -y
      - uses: kopernikusauto/cargo@v1.0.1
        with:
          command: test
          args: --release --lib demo
      - uses: kopernikusauto/cargo@v1.0.1
        with:
          command: test
          args: --release --lib src

  publish:
    name: Publish crates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: kopernikusauto/checkout@v3.3.0

      - name: Install stable toolchain
        uses: kopernikusauto/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name : publish ecal-derive
        run: |
          cargo publish --token ${{ secrets.CRATES_IO_TOKEN || github.token }} -p ecal-derive
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: publish eCAL crate
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN || github.token }} -p ecal-rs
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
